### ISSUE TITLE
How to set overriding permissions

### ISSUE THREAD

**Issue by aussiechief** [dotproject/dotProject#100]
Hello!

I'm trying to set up roles to allow a user to only see specific projects, with all others being hidden from their view. However, if I first deny permissions to all Projects, then create another permission to allow access to just a specific one, the Deny permission overrides the lower-level permission and the user can't see anything.

Is it possible to only allow a user to see projects they own, or restrict them to specific ones?

Thanks for the help. Appreciate it!

**Comment by fatabek** [comment]
Hello,

Not necessary deny permisson all projects. 

1) Create new role and give only "allow"  permisson for "none admin modules" in role list.
2) Give only "access" and "view" permision all tasks in user prereferances - permision tab.
3) Give only "access" and "view" permission company of project and project (whichever you want) in user preferences - permission tab.

Note : If any problem for accessing projects please give "allow" and "view" permissons for "none admin modules" in role list.

B&R

**Comment by Givo29** [comment]
Hi @aussiechief, did fetabek's answer solve the issue you were having? If so, I'll close the issue
