### ISSUE TITLE
Inline images in quilljs: Where to implement database changes

### ISSUE THREAD

**Issue by Givo29** [dotproject/dotProject#103]
I have made the changes we have discussed to the database to allow for quilljs to support long inline base64 encoded images - setting the `task_description` and `task_log_description` to the `LONGTEXT` type and I have implemented a config option to restrict the size of the description fields. 

An issue that I've come to now is that I don't know where I should make the database changes within the source code.. ie whether it should be in `db/dotproject.sql` or in an sql upgrade file.

What are your thoughts on this?

**Comment by ajdonnison** [comment]
It goes in both db/dotproject.sql and in an sql upgrade file (in between releases it goes in upgrade_latest.sql, which gets renamed appropriately on release).  The db/dotproject.sql is used for new installs, the upgrade_*.sql are used for incremental upgrades.  The upgrade scripts need to have a date in the form YYYYMMDD with a single hash and a space before the required change, as the installer works on the last update date found in the database to determine which updates are necessary - this allows for you running the installer multiple times without breaking things.

**Comment by Givo29** [comment]
Okay will do. Thanks
