### ISSUE TITLE
Incompatible dotproject installation

### ISSUE THREAD

**Issue by jmp247** [dotproject/dotProject#108]
Hi,

I recently updated the PHP version on my shared host provider from 5.5 to 7.0.   Now, my dotproject installation no longer works.  I believe this is due to the deprecated mysql functions.  Any recommendations on the best course of action to update my dotproject so that it is compatible and functionable again?  If I revert to 5.5, is there a built-in option to upgrade dotproject?

Appreciate any advise.

Thanks,
Jose.

**Comment by gnovaro** [comment]
Hello,  I made a basic pull request but I think. The better solution is made a new branch. Support php7 is a big feature and introduce compatibility issues,breaking changes, must be a new mayor version like 3.0.0

**Comment by cleary** [comment]
Hi guys, PHP7 is already supported in the devel branch - if you don't feel like jumping to devel then you can certainly look at forking the master and cherry picking the commits from devel.

Alternatively, @ajdonnison would it be worth doing a minor dot release just to introduce the php7 support?

**Comment by osirismx** [comment]
> Hi guys, PHP7 is already supported in the devel branch - if you don't feel like jumping to devel then you can certainly look at forking the master and cherry picking the commits from devel.
> 
> Alternatively, @ajdonnison would it be worth doing a minor dot release just to introduce the php7 support?

Hi, how i can get the devel branch?

**Comment by cleary** [comment]
> 
> Hi, how i can get the devel branch?

```
git clone https://github.com/dotproject/dotProject.git
cd dotProject
git checkout devel
```

**Comment by osirismx** [comment]
> > Hi, how i can get the devel branch?
> 
> ```
> git clone https://github.com/dotproject/dotProject.git
> cd dotProject
> git checkout devel
> ```

Some database changes?

**Comment by ajdonnison** [comment]
@cleary a release has been on my list for a while - really well overdue.  I'm hoping to get it done this week if work allows.

@osirismx I don't think there were any database changes, but it is still safe to run the installer again as it will pick up any interim changes and apply them.

**Comment by osirismx** [comment]
> @cleary a release has been on my list for a while - really well overdue. I'm hoping to get it done this week if work allows.
> 
> @osirismx I don't think there were any database changes, but it is still safe to run the installer again as it will pick up any interim changes and apply them.

It works!, thanks.

Can i use the same spanish locales or i need to get new ones?

**Comment by ajdonnison** [comment]
@osirismx the locales shouldn't have changed, but if you do get a problem please open a new issue on it.

**Comment by osirismx** [comment]
> @osirismx the locales shouldn't have changed, but if you do get a problem please open a new issue on it.

Thanks a lot

**Comment by ajdonnison** [comment]
Given I've now tagged a 2.2.0 release with 7 support I'm going to close this.
