### ISSUE TITLE
The "reset search" button is not working on "Contacts" menu.

### ISSUE THREAD

**Issue by teodorg** [dotproject/dotProject#11]
There are two "reset search" buttons in dotProject - one at Companies and one at Contacts.
The one at "Contacts" doesn't work, on both branches (master and devel). Will do an attempt to fix that.

**Comment by ajdonnison** [comment]
Verified.  Looks like there is a difference in the use of saved parameters.

**Comment by teodorg** [comment]
Glad to see you back! :)

**Comment by ajdonnison** [comment]
@teodorg thanks.  I can't promise I can fix everything immediately, but I will promise not to neglect the project.

**Comment by ajdonnison** [comment]
I think that resolves the issue, can you check and let me know if there are still issues?
