### ISSUE TITLE
/tasks/addedit.js - 601 line

### ISSUE THREAD

**Issue by NicoleDeboua** [dotproject/dotProject#114]
Good day!

I can't create tasks. 
There are error in 601 line, script don't worked. Now delete 601-603 lines in the file..
Please, check which code is required.

Thanks.

**Comment by ajdonnison** [comment]
Can you give a bit more detail:
* What you were doing to trigger the error
* What operating system you are running on
* What browser and version you are running on
* Exact wording of any error message

**Comment by NicoleDeboua** [comment]
OS: WinXP SP3,  browser: Mozila - 52.9.0 (32-бит)
 "Toggle Tools" from the Web Developer menu that are built into Firefox.

Press button "save" in "Add task".  Errors from Mozila Firefox:
1.	ReferenceError: subForm is not defined[Подробнее] …….  index.php:352:2
2.	ReferenceError: subForm is not defined[Подробнее] …..   index.php:406:2
3.	ReferenceError: subForm is not defined[Подробнее] …..     index.php:539:3
4.	SyntaxError: expected expression, got       ……………  addedit.js:651:24
5.	Применение Mutation Events является устаревшим. Вместо них используйте MutationObserver. ………….  quill.min.js:7:147054
6.	ReferenceError: submitIt is not defined[Подробнее] ……   index.php:1:12

**Comment by NicoleDeboua** [comment]
And one more. In dotProject v.2.1.8 tasks saved nice!

**Comment by ajdonnison** [comment]
So what version of dotProject is this?  The latest 2.2.0?  If so, how did you do the upgrade?

It looks like some of the files may be incorrectly copied in, as, for instance, error 4 (SyntaxError) points to an empty line in `addedit.js`.

**Comment by NicoleDeboua** [comment]
Yes, version 2.2.0 and full new installation.

**Comment by NicoleDeboua** [comment]
In addedit.js lines 596-603:

			case 'select-one':
				if (elem.options.length > 0)
                                    try {               
			                to.appendChild(h.addHidden(elem.name, elem.options[elem.selectedIndex].value));
                                    }
                                    catch {
                                        break;
                                    }
				break;

write error - "try ...  catch....".

**Comment by NicoleDeboua** [comment]
On this site: https://www.softaculous.com/softaculous/demos/dotProject
demo version.
So I can't create new task and buttons don't work like on my computer.
May be I'm doing something wrong ??

**Comment by ajdonnison** [comment]
I can create a task there - you need to create a company first, then a project within that company and a task within that project.  How were you trying to create a task?

**Comment by NicoleDeboua** [comment]
Yes. Then most likely there is a problem with  of  java version  on the my computer.

**Comment by ajdonnison** [comment]
In that case I think we can probably close this one.
