### ISSUE TITLE
Files Module - Displays shell_exec() error.... Does shell_exec() need to be enabled in php?

### ISSUE THREAD

**Issue by nwinesett** [dotproject/dotProject#115]
I have been testing my installation of dotProject on my hosted server and frequently get errors when I try things in bulk.  I have posted previously and am trying to resolve those errors one by one.

When testing the Files module, whenever I add a new file, I get the error below.

Does shell_exec() need to be enabled and is that relatively safe?  My current setting in my php.ini file is:
`disable_functions = passthru,shell_exec,system`

The file still uploads successfully, but the error popping up each time makes it impractical to use in a work environment.

Here is the error that appears after adding a file:

```
Warning: shell_exec() has been disabled for security reasons in /home/averywh0/public_html/awwlegal.com/projects/modules/files/files.class.php on line 260

Warning: Cannot modify header information - headers already sent by (output started at /home/averywh0/public_html/awwlegal.com/projects/modules/files/files.class.php:260) in /home/averywh0/public_html/awwlegal.com/projects/classes/ui.class.php on line 585
```

**Comment by ajdonnison** [comment]
This is where it parses the file to allow us to pull keywords for indexing.  Currently this uses an external process - in our case `/usr/bin/strings` - you can see which ones in System Admin in the Files section.

Ideally we should default to an all-PHP parsing, however you can get around this - with the removal of the ability to search files by keyword - by clearing those out and leaving them blank.

**Comment by nwinesett** [comment]
@ajdonnison 
Ok, That is very helpful.  I deleted those paths and it worked much faster and did not give me an error:

![image](https://user-images.githubusercontent.com/60666725/79410913-370a4380-7f67-11ea-8a40-0230f9383c89.png)

So, I assume that means you need to either 1) delete those paths or 2) enable shell_exec() on the server (assuming your web host will let you).   Correct?

**Comment by ajdonnison** [comment]
Correct.
