### ISSUE TITLE
Custom Fields / Select List:  What is the recommended way to designate either a default entry or a blank entry?

### ISSUE THREAD

**Issue by nwinesett** [dotproject/dotProject#117]
Custom Fields / Select List:  What is the recommended way to designate either a default entry or a blank entry?

In this image for a New Project entry, you can see I've made some custom fields.  For "Property County," I've made a list of counties to select from the pull-down box.  The box defaulted to the first county alphabetically.  However, not all our projects need county information, so I'd like to leave it blank by default.  Additionally, I would like our primary county to be at the top of the list (even thought it is not first alphabetically).
![image](https://user-images.githubusercontent.com/60666725/79669428-00a81080-8181-11ea-8074-a60ce663fb3f.png)

I've made the custom fields from here:
System Admin | Custom Filed Editor | "edit property county"
![image](https://user-images.githubusercontent.com/60666725/79669535-d571f100-8181-11ea-8719-1d268037ee79.png)

I've noticed in System Admin | System Lookup Values, that they order entries by doing something like the following:  -1| text 0| 1| text2 2| text 3
![image](https://user-images.githubusercontent.com/60666725/79669609-516c3900-8182-11ea-91a2-819016c60ca1.png)

I've made some of my own changes in here, such as for Project Type using the number and the pipe symbol and it works great.  Neither the number nor the pipe symbol (|) appear in the New Project pulldown box.  I've tried to implement this in the Custom Fields Editor as you can see above, but I'm not having success.

I'm not sure exactly what the HTML Tag Options is for or how to use it, but I presume it's for making something bold or italics or other formatting.  Also, I'm not sure if it applies to the entire list or a single entry.  I can't find an example of what to put in there on github.

Does anyone have a suggestion for the best way to **1) make a blank entry be the default**, 2) **make a particular entry be the default**, and 3) **reorder the list non-alphabetically (without the use of numbers)**?

**Comment by ajdonnison** [comment]
Custom fields are completely different to system lookup values, and the parsing logic doesn't work the same.  While there is a "TODO" in the code to support field ordering other than alphabetical, there is no supporting code there yet, so it looks like you are stuck with alphabetical.
One way of putting a first entry that can be used as a default is to use something like "-- N/A --" which will sort alphabetically before anything else - not exactly a blank, but should be at least understandable.

The HTML tag options are used by the field parser to add attributes to the HTML being generated for the edit form, however it looks like they may not be all that useful as they get stripped out with the default interface style.  I suspect it will need a bit of work.

**Comment by nwinesett** [comment]
@ajdonnison 

--N/A-- works for me, and it looks like I can use numbers as well to order them, although the number shows.  Tabbing to the field and starting to type the county works, so I've decided to not use the numbers.

I don't see the ToDos or a feature request section.  Where to you list the ToDos?

**Comment by ajdonnison** [comment]
The TODO is in the comments in the code, it is used by programmers to remind themselves of something they want to do without opening an issue or task.

**Comment by nwinesett** [comment]
Since it is in the TODO and the workaround has been discussed, I'm going to close this issue.  Thanks!
