### ISSUE TITLE
"My Tasks To Do" page:  "mark as finished" tasks not working

### ISSUE THREAD

**Issue by nwinesett** [dotproject/dotProject#118]
Using Version 2.2.0

On **MY TASKS TO DO** page:

1. Checkmark the unfinished task
2. Select "mark as finished" in bottom right pull-down box
3. Click "update tasks" button

Task does not update and is NOT marked done throughout the program.  However, in Project Designer module, checking the task and marking task as finished does work properly... so have to use that for now until fixed.

**Comment by ajdonnison** [comment]
Can you provide the URL (mainly the m= and a= parameters) and perhaps a screenshot?

**Comment by nwinesett** [comment]
@ajdonnison 

../projects/index.php?m=tasks&a=todo

![image](https://user-images.githubusercontent.com/60666725/79840409-77a8f900-837b-11ea-9ff9-f05621f669f6.png)
![image](https://user-images.githubusercontent.com/60666725/79840513-9d360280-837b-11ea-97a2-3e0bc09f9207.png)

**Comment by ajdonnison** [comment]
@nwinesett I've pushed a change to the devel branch which fixes this.

**Comment by nwinesett** [comment]
I've tested this and it appears completely fixed.  Thanks @ajdonnison! :)
