### ISSUE TITLE
In dotproject version 2.2.0, the URL of the static resource image shows two ports.

### ISSUE THREAD

**Issue by zj507071** [dotproject/dotProject#120]
In dotproject version 2.2.0, the URL of the static resource image shows two ports.
user version info：
dotproject 2.2.0
Windows 10 x64
AppServ 9.3.0
PHP 7.3.10
MySQL 5.7.21
![dotproject_20200421090850](https://user-images.githubusercontent.com/19506592/79814130-151e2000-83b0-11ea-9057-abf0af1a5ac6.png)

**Comment by nwinesett** [comment]
Hi.

Thats the alt text for the images showing.  I think that your browser is set to not allow images, so it shows the "alt" text instead.

**Comment by zj507071** [comment]
> 
> 
> Hi.
> 
> Thats the alt text for the images showing. I think that your browser is set to not allow images, so it shows the "alt" text instead.


My modify the file “base.php”
![20200421160758](https://user-images.githubusercontent.com/19506592/79842329-3d774000-83eb-11ea-8d2a-e68433c4b6c5.png)

**Comment by ajdonnison** [comment]
@zj507071 looks like it is a holdover from older webservers. The change you've done will work on your system - the pushed change should work more widely.
