### ISSUE TITLE
What login and password should I enter after installation?

### ISSUE THREAD

**Issue by it19862** [dotproject/dotProject#13]
Somewhere it was written that "admin" "passwd".
But it does not work
![3147](https://user-images.githubusercontent.com/18245828/38614421-ca027e02-3d95-11e8-879f-204f3179a5b7.jpg)

What login and password should I enter after installation?

**Comment by teodorg** [comment]
Hello, the default admin username and password are these, mentioned by you.
Do you have write access to the SQL database? If so, try to overwrite the password field and try again.

The relevant table is "users" (could be dotp_users), the field is "user_password" and it should be MD5 hashed.

something like this:

UPDATE users SET user_password=MD5("passwd");

**Comment by teodorg** [comment]
5F4DCC3B5AA765D61D8327DEB882CF99

Here is an md5 hash that represents the word "password" (without the
quotes, of course).
Put it there, login and change.

**Comment by it19862** [comment]
@teodorg 
I did so.
Correctly?

Does not work
![3179](https://user-images.githubusercontent.com/18245828/39398804-e989d624-4b1b-11e8-81a1-caaa2209c441.jpg)

**Comment by teodorg** [comment]
Ouf, contact me on private, if you want. I will login and solve it for you.

**Comment by it19862** [comment]
@teodorg 
How to do it?
I need to contact you by email?

**Comment by teodorg** [comment]
tgeorgiev at stonard dot eu

**Comment by it19862** [comment]
@teodorg 
Sorry, but I did not understand what your message means.

Could you write more in detail what is required of me to get help from you.

Thank you.

**Comment by xSmorpheusSx** [comment]
I have a similar problem but I am definitely sure that username and password are correct. After complete install of dotproject, I reach the login view, type in the default username "admin" and "passwd" but login seems to fail. After clicking on "Login" the application shows the login page again without any information if anything went wrong. I looked at the user table and checked the md5 encoded default password "passwd". The password matches the encoded String "passwd" so it seems to be correct. Does anybody know why login fails despite valid login information?

**Comment by teodorg** [comment]
Ok, it seems that there is obviously something wrong with the installation.
Could you contact me on private and provide me with access, so I can dig to
the bottom of this?

**Comment by xSmorpheusSx** [comment]
What do you mean with provide me with access? You mean some remote sesssion? I can provide you my system information. Trying to install "dotproject" on XAMPP 3.3.2 with MySql, Apache 2.4.29, Tomcat 7.0.56 and PHP Version 7.1.12. There are no dotproject mods installed.

**Comment by renatorroliveira** [comment]
Any luck from anyone? Same problem here

**Comment by teodorg** [comment]
Guys, I played several times with 2.1.9. The install procedure goes smoothly and I login in without any troubles.
Platform: Linux, Centos 6 and 7 , Apache 2.2, MySQL 5.1, PHP 5.3. If someone needs a helping hand in installing - just do let me know. I would gladly do it in 10min for you.

**Comment by renatorroliveira** [comment]
I see, my system is running PHP 5.6 and MySQL 5.5, this can be an issue?

**Comment by ajdonnison** [comment]
It should also work with PHP 5.6 and MySQL 5.5.  It will work with Apache and also with Nginx using php-fpm.  If you get into trouble with the login look for any errors in your system log files, and report them here.  Also read above for how to check the database.

**Comment by lgarmendia76** [comment]
There's something wrong when updating an existing installation. I was coming from 2.1.6 and no user could get in. I could see that the user roles were gone, so all users were set Inactive. In order to make them active you need to assign them a role. Apart from that, I also lost some other information like cost code. I can't be sure if there's something else, too. I had to revert back to 2.1.6 and restore user roles. I wanted to try 2.1.9 to see which improvements it has, but I can't. That's a shame.

**Comment by teodorg** [comment]
I would suggest that you suppress the anger inside you and see how we can dig into that problem and solve it together?

**Comment by lgarmendia76** [comment]
> I would suggest that you suppress the anger inside you and see how we can dig into that problem and solve it together?

Dear @teodorg, I was trying to give some insight. I'm no programmer, so I'm sorry for giving limited information. But there was no anger in my words, only the aim to provide some info. I'm so grateful to the developers.

**Comment by ajdonnison** [comment]
@lgarmendia76 can you give us a bit more information?  Things like:
* What operating system
* What version of PHP
* What version of MySQL
* Nginx or Apache and version
* Any errors or messages that showed up during the upgrade
* How did you perform the upgrade?
That would make it a lot easier to provide assistance.

**Comment by lgarmendia76** [comment]
- Windows Server 2008 R2
- Based on Bitnami Wamp stack 5.4.17.0:
   * PHP 5.4.0
   * MySQL 5.0.10
   * Apache 2.4.0
- I tried several installations. First from my remote computer:
   * A clean install creating a new DB. Had some problems creating the DB.
   * Then I tried and upgrade by duplicating the current installation folder and updating the files over it. Again, had problems managing the DB, it wouldn't connect to it.
Then, from the server itsefl (remote connection):
   * I could manage to upgrade the duplicated folder and I got in with admin user. That's the moment when user roles were gone.

**Comment by ajdonnison** [comment]
@lgarmendia76 I've moved this to a new issue as it is not the same as the original and is therefore likely to confuse - let's follow this up on the new issue (#31 )

**Comment by lgarmendia76** [comment]
I'm not that sure about it. Can you try to get into mySQL and check the admin's status? If it's "inactive", then it can be all related.

**Comment by ajdonnison** [comment]
@lgarmendia76 it is not the same issue - the oiriginal issue was about login and password for a new installation - your issue is about updating an existing installation - and has nothing to do with login and password - please don't hijack other threads.

**Comment by ajdonnison** [comment]
By default the admin user is `admin` with a password of `passwd` . If you didn't see any errors on the database build page then it should work.  If it doesn't, and doesn't show an error on the login page then check your web server error log for clues.

There was a known issue with 2.1.9 and certain versions of MariaDB (which is often installed as MySQL on Linux distros).  It may also be a problem with other databases.  However, that would usually result in error messages in the install phase when it builds the database. Either way it is probably a good idea to try with the `devel` branch and see if that works:

https://github.com/dotproject/dotProject/archive/devel.zip

**Comment by zhjq** [comment]
same problem.  can't login with "admin" - "passwd" . any solution?

**Comment by zhjq** [comment]
devel branch the same with master

**Comment by renatohfbranco** [comment]
Fellows, same here.

First, sorry for the bad English.

We performed a brand new installation with:
- Linux Mint 19.3 / Xubuntu 18.04.03 (doesen't matter - it happens with both distros).
- XAMPP 5.6.40
- dotProject 2.19
- no modules

When we logged in the localhost (http://localhost/dotproject), everything works. We are able to start the application and to input all the information that we need.
But, when we reach the hosted machine from other ones, it does not allow to login. Even with the localhost getting out and getting back to it, it cannot access the application. i.e. http://application_host_address/dotproject.

When we try to access from other machines than the host we get this on the browser address bar:
1st attempt: http://application_host_address/dotproject/index.php?dotproject=tf5g68kjg9ept6tr7j0lbgqt70
2nd attempt: http://application_host_address/dotproject/index.php?dotproject=tf5g68kjg9ept6tr7j0lbgqt70&dotproject=apsld9c1fhmrlek1075oo07eh5
3rd attempt: http://application_host_address/dotproject/index.php?dotproject=tf5g68kjg9ept6tr7j0lbgqt70&amp;dotproject=apsld9c1fhmrlek1075oo07eh5&dotproject=m5uol48b932rfr5gucc97ac4g7

and goes on getting bigger the php instruction.

Does anybody know what it could be or the sollution for it?

Thanks!!!!!!
