### ISSUE TITLE
possibly redundant code in Index.php

### ISSUE THREAD

**Issue by maxxatgit** [dotproject/dotProject#130]
Hi,

I'm hosting DP version 2.2 on a linux server, and mod_sec complains about the iframe code at line 310 in index.php, and I get a white screen.

I commented out the code in question, and DP seems to be working ok (no more white screen). I haven't really put any data in yet, just getting it up and running... I'm just wondering why that code is there?

I'm *not* complaining, I really appreciate the intelligence and volition that goes into developing open source software, just asking a question.

Also, I'm happy to report back if anything breaks as a result of the code being commented out.

Regards,
Paul

**Comment by ajdonnison** [comment]
It is actually used by the tasks organiser.  I suspect it could be done without an iframe, although I suspect that you cannot use 'organise tasks' when this is commented out - otherwise everything else should work.

**Comment by maxxatgit** [comment]
Thanks for the reply!

I have adjusted mod_security so I can leave the code un-commented.
I'm closing this issue...

Thank you for the superb software!
