### ISSUE TITLE
Localization is not working

### ISSUE THREAD

**Issue by jvalen36** [dotproject/dotProject#132]
After upgrade from 2.1.7 the Spanish Locale stop to work

please help

**Comment by juliangonzalezblanco** [comment]
ya solucionaste? estoy en la misma situacion...

**Comment by jvalen36** [comment]
hola, pero no recuerdo como :-( 

creo que copie los rchivos de español de la version anterior. si recuerdo te aviso.

**Comment by juliangonzalezblanco** [comment]
vale, seria de mucha ayuda... o si me puedes pasar la carpeta "es", ya he probado la que esta en dotprojectmods pero no funciona... gracias ;)

**Comment by jvalen36** [comment]
prueba los adjuntos.

On 2020-10-20 20:20, juliangonzalezblanco wrote:

> vale, seria de mucha ayuda... o si me puedes pasar la carpeta "es", ya he probado la que esta en dotprojectmods pero no funciona... gracias ;) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/dotproject/dotProject/issues/132#issuecomment-713231162
[2]

**Comment by juliangonzalezblanco** [comment]
Creo que  esos son los que ya probe, uno es  del 2004 y otro de 2003. pero no me funcionaron :(

**Comment by ajdonnison** [comment]
You probably need to give a bit more context - like what does "not work" mean?  Is it showing the English versions instead, or showing garbage, or what?  Are there any errors listed anywhere?
