### ISSUE TITLE
Dot project mysql PHP issue

### ISSUE THREAD

**Issue by TA02** [dotproject/dotProject#133]
Hi While accesing dot project geting below warning

Warning: mysql_connect(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/html/dotproject/lib/adodb/drivers/adodb-mysql.inc.php on line 364 FATAL ERROR: Connection to database server failed.
 For reference please find screenshot.
Request you to provide solution 

Thanks,
Neeta
![dotproject issue](https://user-images.githubusercontent.com/62753091/86097554-79591080-bad2-11ea-9f41-c149f75da8c3.PNG)

**Comment by ipeevski** [comment]
Usually caused by mis-configured database setup.
What does your `/etc/mysql/my.cnf` file look like?

**Comment by GwynethLlewelyn** [comment]
I'd say that this issue can be closed; because @TA02 so kindly gave us his URL to their dotProject installation, we can easily see that there are no more MySQL errors...
