### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by LindolfoJunior** [dotproject/dotProject#14]
Hi!

I am installing dotProject on PHP 7. * and on setup it is stating that mysql driver is not supported by php, however, by searching the documentation, mysql support has been deprecated and now only supports mysqli.

Could you check?

The link where i get the information:
https://secure.php.net/manual/en/mysql.installation.php

Sorry by my bad english

**Comment by teodorg** [comment]
Hello, what distro are you trying to install it on ?

**Comment by ajdonnison** [comment]
You need to pull the devel branch as it has been rewritten to get over this.

**Comment by LindolfoJunior** [comment]
@teodorg Im trying to install the last one on Ubuntu 16 with PHP 7.2.

**Comment by LindolfoJunior** [comment]
@ajdonnison how can i do this? 

Sorry for the newbie question...

**Comment by ajdonnison** [comment]
@LindolfoJunior you can use the Branch selection on the Code page and then the Download ZIP link, or if you've cloned the repo you can use `git checkout devel`.  Or just use the URL https://github.com/dotproject/dotProject/archive/devel.zip

**Comment by LindolfoJunior** [comment]
@ajdonnison 
Tks! 
Now the config works (the git default dont work) with errors. 
If i click on <install db & config> the install fail on create database and tables, but, if i click on <only db>, it create database tables.

When i try to access in root i got error (
![browser connect error](https://user-images.githubusercontent.com/38046370/38991749-157fc2f2-43b5-11e8-9886-0ded5b3bbefa.JPG)
), but, when i try connection using the user and pwd it work (). 

How do i config to access the dotProject?

**Comment by LindolfoJunior** [comment]
Hi! I have found the error. The dotproject cant use password with '@'. I have change and it works.
