### ISSUE TITLE
patch installation

### ISSUE THREAD

**Issue by juliangonzalezblanco** [dotproject/dotProject#141]
Hello I have a patch to solve the problem of "You have chosen to log in using an unsupported or
disabled authentication method..." but I do not know how to install it, any volunteer to help me please

**Comment by juliangonzalezblanco** [comment]
ALREADY COULD

**Comment by ipeevski** [comment]
Attach the patch so we can have a look

**Comment by juliangonzalezblanco** [comment]
hello, it won't let me attach, but I send you the link so you can download it, thanks
link: https://sourceforge.net/p/dotproject/patches/229/

**Comment by ipeevski** [comment]
That patch is already in the codebase (both `master` and `devel` branches)

**Comment by juliangonzalezblanco** [comment]
Do you know in which folder or in which part?
I can not find it

**Comment by ipeevski** [comment]
https://github.com/dotproject/dotProject/blob/devel/classes/ui.class.php#L719

**Comment by juliangonzalezblanco** [comment]
Yes, but what should I do? I do not understand

**Comment by ipeevski** [comment]
Are you using the latest version? Downloaded from GitHub?
If so, your issue is most likely a different one from the one solved in the
patch. The patch is already applied to the latest version from what i can
tell.

**Comment by juliangonzalezblanco** [comment]
Yes, I have the latest version. When I translated into Spanish, the login did not work. that's why I looked for the patch, but I don't know how to put it on or how to use it.

**Comment by ipeevski** [comment]
And what I was trying to explain is that the patch won't help. Can you
attach your translation please?

**Comment by juliangonzalezblanco** [comment]
of course... 
https://sourceforge.net/p/dotmods/patches/69/

thanks!

**Comment by ipeevski** [comment]
I cannot reproduce the issue using this language.
Can you please confirm you are using the latest release from here:
https://github.com/dotproject/dotProject/releases/tag/v2.2.0

What's the version number, listed on the login screen (under the login box)?

Also, from what I can tell, the translation you've pointed at had kept the word for "login" as "login" (in file locales/es/common.inc:145) so that shouldn't have caused this problem in the first place ...

Also, the error message you get in the first place "You have chosen to log in using an unsupported or
disabled authentication method" doesn't exists in the latest version.  The new version's message is "You have chosen to log in using an unsupported or disabled login method", so I believe you have the wrong dotProject version.

**Comment by juliangonzalezblanco** [comment]
I have version 2.2.0 is more install from softaculous, and if the error is in the word "login" that is used in the translation, fix that problem. I just wanted to know how to install the patch or how to use it. thank you very much for your help

**Comment by ipeevski** [comment]
The patch is no longer valid as it is for an older version.
This is no longer an issue as far as I can tell.

**Comment by juliangonzalezblanco** [comment]
I understand you, but it gave me an error.
however I thank you for the collaboration 😉

**Comment by ipeevski** [comment]
What was the translated value for 'Login'? I'll try that as well.
Maybe there is something weird with the softaculous version

**Comment by juliangonzalezblanco** [comment]
I don't remember well anymore, if I'm not bad it was "iniciar sesion" but I do not remember very well why I changed it a few days ago due to the error and left it in English, I mean the button without translation

**Comment by juliangonzalezblanco** [comment]
![20201210_193713](https://user-images.githubusercontent.com/69259943/101846597-515ce700-3b1f-11eb-89e8-87edd08936ce.jpg)

**Comment by ipeevski** [comment]
No problem. Is it working ok for you now?
I see you've closed the ticket - assuming you are ok with workaround.

**Comment by juliangonzalezblanco** [comment]
Yes, it is that I had created it because I could not solve it. but I already look good and it works
thank you very much for your help
