### ISSUE TITLE
Problem Gantt chart generation, XAMPP installation in Mac

### ISSUE THREAD

**Issue by bernardojn151** [dotproject/dotProject#147]
I installed dotproject in XAMPP. Everything is ok but no gantt view. Someone could help me? I changed the memory configuration to 64M and 128M but nothing change

**Comment by bernardojn151** [comment]
<img width="1218" alt="Screen Shot 2021-02-14 at 20 12 55" src="https://user-images.githubusercontent.com/79064505/107892020-0be2de80-6f01-11eb-8416-80d23eefe465.png">

**Comment by ipeevski** [comment]
If you right click the image and make it open in a new window, does it show a text error?

**Comment by bernardojn151** [comment]
Hi Ivan, I fixed the gantt chart view problem using MAMP. No warnings during installation in MAC, thank you

**Comment by stech04** [comment]
Hi @bernardojn151 I'm having the same problem about the Gantt chart not showing up. I'm running the dot project on ubuntu 14.04 with lamp server. Do you think you can help me? Thanks in advance!

**Comment by Rafael-Rueda** [comment]
@stech04
try do:
`sudo apt-get install php7.4-gd`
then:
`sudo systemctl restart apache2`

It might work. Change the version of php to your respective version. Currently, version 8 is not compatible with dotproject, this is why i am using version 7.4 in this case. This solved my issue.

**Comment by stech04** [comment]
Thank you very much for your response!!
