### ISSUE TITLE
Dotproject error on PHP 7.2 - Session

### ISSUE THREAD

**Issue by LindolfoJunior** [dotproject/dotProject#17]
Hi!,

I want to inform that dotproject has a fail in code that have to be changed
in /includes/session.php line 195. have to comment this line to DP works.

**Comment by ajdonnison** [comment]
Now fixed in devel branch, will make it into next release

**Comment by m0m0g33k** [comment]
Hi!,

In addition I had to modify the line #190, changing the function **session_name()** to **session_id()**.

Regards.
