### ISSUE TITLE
NFGH

### ISSUE THREAD

**Issue by Executive-assist03** [dotproject/dotProject#170]

**Comment by Executive-assist03** [comment]
@ajdonnison, @bhuvankrishna, @abnerrizzi, @cleary can you please take a look, please?

**Comment by cleary** [comment]
sorry I'm no longer working on this project

**Comment by Executive-assist03** [comment]
@dotproject-devops @tjcomserv someone please?

**Comment by abnerrizzi** [comment]
Well I see your desperate for the solution, but, have you checked the collation, localization, and things related to language, charset and related things ?

can you show your phpinfo() results ?
