### ISSUE TITLE
Errors in Add Company.

### ISSUE THREAD

**Issue by LindolfoJunior** [dotproject/dotProject#19]
Hello!
There is an error in /classes/CustomFields.class.php at line 644 that refers to trying to count the custom fields, however, when I go to the company registry page it displays the error below.

To fix it, I suggest the fix for the following code:
return ($this->fields)?count($this->fields):0;

Below is the screenshoot.
![error](https://user-images.githubusercontent.com/38046370/39367884-6e90785a-4a0e-11e8-824e-9caf86224b77.JPG)

**Comment by ajdonnison** [comment]
Thanks for the report - I've chosen a slightly different approach that gets rid of other potential errors.
