### ISSUE TITLE
Warning on 'Time Worked' field in 'View Task' screen

### ISSUE THREAD

**Issue by Nocturnal-2** [dotproject/dotProject#24]
I am thrilled to some activity on this project! Thanks to everyone how is keeping this active!!

# Issue

I have downloaded version 2.1.9. I am seeing the warning message "Warning:  A non-numeric value encountered in C:\xampp\htdocs\dotProject\modules\tasks\view.php on line 234" in front of value '0' in the field 'Time Worked:' in 'View Task' screen.

# Version details

I am using the latest version of XAMPP with Apache/2.4.33 (Win32) OpenSSL/1.0.2o PHP/7.1.17

**Comment by Nocturnal-2** [comment]
Interestingly, when I add a log to the task this warning disappears!

**Comment by ajdonnison** [comment]
The warning will only occur when there are no tasks - however it probably still needs to be addressed - look for an update soon.

**Comment by ajdonnison** [comment]
When I looked at that code I wondered how it ever worked:)  Should now behave a lot more consistently
