### ISSUE TITLE
Exporting and importing data

### ISSUE THREAD

**Issue by Nocturnal-2** [dotproject/dotProject#25]
Is there a way to export and import the data from dotProject?

I have created huge amount of data in my local installation. I will like to export that and import into the installation in my web server. Is it enough if I export and import the database contents?

**Comment by ajdonnison** [comment]
If you are just trying to duplicate the data from your local system you can use mysqldump to dump the database and load that onto your web server.  If you are trying to merge data, then that is more difficult.  There is a backup module on dotmods, however I'm not sure it is up to date with the current codebase - and even then it just does a dump/restore - albeit without needing direct mysql access.

**Comment by Nocturnal-2** [comment]
Thank you @ajdonnison 

I am just trying to duplicate. I will try mysqldump.
