### ISSUE TITLE
Dependency Tracking - date not change 

### ISSUE THREAD

**Issue by fatabek** [dotproject/dotProject#27]
When we are update subtask new date (for example 1 week after) the main task start date automatically chaning. But if we will update subtask old date (for example change date 2 weeks ago) the main task date not chaning.

How we can fix this ?

Can you help us ?

Thanks.

**Comment by ajdonnison** [comment]
You can't automatically move the end date before the start date, which is what I think you are suggesting.  It would not make a lot of sense.  Can you perhaps provide some screen shots?

**Comment by fatabek** [comment]
First of all my english not good, sorry for this.
I want to explain 
Case 1 we create 3 task
![case 1-1](https://user-images.githubusercontent.com/41823969/47987070-a253b300-e0ef-11e8-8824-a05dbceb1f2e.JPG)
Case 2 we change subtask "00-01-02" start date
![case 1-2a](https://user-images.githubusercontent.com/41823969/47987079-a97ac100-e0ef-11e8-8fb9-2050fe144a83.JPG)
But "00-01" and "00-01-01" tasks   start date not change
![case 1-2b](https://user-images.githubusercontent.com/41823969/47987087-af70a200-e0ef-11e8-835e-28b58524baf8.JPG)

**Comment by fatabek** [comment]
As you see the screenshots In this task structure we can't make any Dependencies in parent and child tasks.
![task 00-01 dependencies screen](https://user-images.githubusercontent.com/41823969/47989961-5573da80-e0f7-11e8-807e-f5c0d9fb4374.JPG)
![task 00-01-01 dependencies screen](https://user-images.githubusercontent.com/41823969/47989964-586ecb00-e0f7-11e8-9c1b-60b4f1e8999c.JPG)
![task 00-01-02 dependencies screen](https://user-images.githubusercontent.com/41823969/47989975-5d337f00-e0f7-11e8-9f31-30f51254e85a.JPG)

**Comment by ajdonnison** [comment]
You haven't set any dependencies so it won't change anything.  In the Dependencies tab you will see to the left the list of tasks you can depend upon and on the right the list that are dependencies.  You can move items from one window to the other by clicking on the name and using the two buttons `<` and `>` at the bottom of the screen.  You can also click on the s`Set task start date based on dependency`.

**Comment by fatabek** [comment]
Sorry my english, Ok I know this solution, but for this solution : we must see in 00-01-02 in the dependencies page left side of tasks 00-01-01. But we don't see therfore we can't add.

**Comment by ajdonnison** [comment]
First, you need to turn on dependency tracking - otherwise nothing happens.  Then you probably are looking to set the parent task to "Dynamic Task", then it will change based upon its children - dependencies are setting up a relation outside of parent/child.

**Comment by fatabek** [comment]
Thanks a lot. It's solved.
