### ISSUE TITLE
start day of the week

### ISSUE THREAD

**Issue by juanykty** [dotproject/dotProject#29]
I want to change the start day of the week 
![image](https://user-images.githubusercontent.com/30271703/43868087-bd8a6d68-9b20-11e8-9aac-70ea0be17771.png)
I accommodate the days in the system configuration but i can't see changes on the calendar

**Comment by ajdonnison** [comment]
The start day of the week is handled by the locale, and is defined in PEAR/Date.  We don't try and change that in dP.
