### ISSUE TITLE
Installation URL in README is a dead link

### ISSUE THREAD

**Issue by cleary** [dotproject/dotProject#3]
The dotproject/README provides the following url for installation assistance, but it's a dead link:
http://docs.dotproject.net/index.php/Installation

**Comment by ajdonnison** [comment]
That site was on a very old and very buggy version of a wiki that is no longer supported and it was becoming a target for malware and spammers.  We will progressively start moving the content to the wiki link here at GitHub.

I've removed the link from the README (and I know that isn't a great solution, but it will reduce confusion at least for the moment) and will keep this open until we've got at least some basic documentation available.

**Comment by cleary** [comment]
Yep, no probs - wasn't sure if it was an easy translation or not so I figured I'd log it :)
