### ISSUE TITLE
Problems logging in

### ISSUE THREAD

**Issue by wagnersl2018** [dotproject/dotProject#30]
Someone can help me, because I installed dotproject, but when the first log is done, the error below appears, but as soon as I ask to reload the page the system runs normal.
Someone can help me with this error.

Warning: Declaration of LDAPAuthenticator::userId($username) should be compatible with SQLAuthenticator::userId() in /home3/healthgd/www.healthgdi.com.br/hsc/classes/authenticator.class.php on line 362

Warning: Cannot modify header information - headers already sent by (output started at /home3/healthgd/www.healthgdi.com.br/hsc/classes/authenticator.class.php:362) in /home3/healthgd/www.healthgdi.com.br/hsc/classes/ui.class.php on line 577

**Comment by ajdonnison** [comment]
Try it with a fresh pull of the devel branch and let me know.

**Comment by bejula** [comment]
I am having this error: (Warning: Declaration of LDAPAuthenticator::userId($username) should be compatible with SQLAuthenticator::userId() in /home/lugajuco/public_html/projects/classes/authenticator.class.php on line 362

Warning: Cannot modify header information - headers already sent by (output started at /home/lugajuco/public_html/projects/classes/authenticator.class.php:362) in /home/lugajuco/public_html/projects/classes/ui.class.php on line 577)
![SnipImage](https://user-images.githubusercontent.com/54394696/63516567-76be7f80-c4ed-11e9-9863-18e1080ffb09.JPG)
