### ISSUE TITLE
Updating from 2.1.6 issues - Windows Server 2008 R2

### ISSUE THREAD

**Issue by ajdonnison** [dotproject/dotProject#31]
- Based on Bitnami Wamp stack 5.4.17.0:
   * PHP 5.4.0
   * MySQL 5.0.10
   * Apache 2.4.0
- I tried several installations. First from my remote computer:
   * A clean install creating a new DB. Had some problems creating the DB.
   * Then I tried and upgrade by duplicating the current installation folder and updating the files over it. Again, had problems managing the DB, it wouldn't connect to it.
Then, from the server itsefl (remote connection):
   * I could manage to upgrade the duplicated folder and I got in with admin user. That's the moment when user roles were gone.

_Originally posted by @lgarmendia76 in https://github.com/dotproject/dotProject/issues/13#issuecomment-436167606_

**Comment by lgarmendia76** [comment]
You get that information during the installation process.

**Comment by ajdonnison** [comment]
You say you had some problems creating the db, and later that it had problems connecting to the db.  Do you have any error messages or screen shots that would assist?

**Comment by ajdonnison** [comment]
@lgarmendia76 did you install from the devel branch or was it the master?  If master, please try again with devel.

**Comment by ajdonnison** [comment]
@lgarmendia76 try using this version: https://github.com/dotproject/dotProject/archive/devel.zip - this is the `devel` branch of the repository and contains the latest fixes - they get merged with `master` at a release.

**Comment by lgarmendia76** [comment]
Thanks @ajdonnison. I don't think I'll do it immediately, as I need some spare time to update it. I'm just the CTO of a small company, we don't have an IT manager...

**Comment by ajdonnison** [comment]
No problem - I'll leave the issue open until you can get back to me.

**Comment by ajdonnison** [comment]
Given it is almost 12 months since last contact I think we can call this closed.
