### ISSUE TITLE
Installation/Logging In/Running

### ISSUE THREAD

**Issue by deehill** [dotproject/dotProject#32]
Hi.

Did a "download/clone" of the latest dotproject code/project (nov18/2018).

Did the complete setup of the apache/mysql/docRoot dir. 
-Copied the files, set the permissions/group/etc.. 

I get the http://1.2.3.4/dotproject -- which displays the user/login dialog (along with a * browser needs cookies msg)

When I insert the test user/passwd --- admin/pass -- I get a login err.

The /var/logs/httpd/test_log had the  
[Mon Nov 19 10:59:27.933744 2018] [php7:warn] [pid 17531] [client 74.178.139.162:51898] PHP Warning:  Declaration of LDAPAuthenticator::userId($username) should be compatible with SQLAuthenticator::userId() in /var/www/html/dotproject/classes/authenticator.class.php on line 362, referer: http://104.248.125.83/dotproject/

-but I corrected the userId function so this err msg is no longer being generated.

Any thoughts/comments??

Given this test is being run on a test cloud server.. I can provide complete access if required..

thanks

**Comment by ajdonnison** [comment]
It appears you were able to get past this error - although you probably shouldn't have put that log extract unedited.  If you grab the devel branch, it should resolve this issue.

**Comment by deehill** [comment]
Hi. Thanks.

Downloading/installing from the download/clone (tgz) worked. Turns out it was a typo.. (keypad issue!.

thanks

**Comment by Givo29** [comment]
Hi @deehill,

I came across this issue log while researching a similar issue and found that the second link you provided us is still an active dotproject instance that is able to be logged into with using the default dotproject credentials.
Just thought I'd let you know in case this was an oversight.
