### ISSUE TITLE
Setting the secure/email process for using gmail/smtp

### ISSUE THREAD

**Issue by deehill** [dotproject/dotProject#35]
Hi.

Trying to configure the test app to use gmail/smtp.

Gamil can use SSL/TLS

Server Address: smtp.gmail.com
Username: Your Gmail Address (e.g. example@gmail.com)
Password: Your Gmail Password
Port Number: 587 (With TLS)
Alternative Port Number: 465 (With SSL)

Haven't been able to get the test app working to send test emails. If you have suggestions, feel free to post. 

I've implemented the above, selecting TLS as well as SSL, - using the TLS checkbox. 

Thanks..

**Comment by ajdonnison** [comment]
If you have 2FA enabled on your Google account, make sure you've created an application password for dotProject and are using that, and not your regular password.

Check the error log for messages from libmail - it should give you an error indicating what is going on - if not you may need to increase the debugging level in System Admin.  One of the more common errors is that if you are using a test domain Google will refuse to talk to it as the hostname is not resolvable.  The error from Google tends to include a link to a support article with more information.

**Comment by ajdonnison** [comment]
Turns out there was an issue with the login sequence - this should now be resolved.
