### ISSUE TITLE
Lost/Forgotten Password -- Appears to do a reset of password even though email fails

### ISSUE THREAD

**Issue by deehill** [dotproject/dotProject#36]
Hi.

In testing the app, did a lost password test. The app appears to have reset the password even though the app didn't complete the sending of the lost password email. 

Might be worth having logic to allow a user/admin to "test" the smtp configuration process.

**Comment by ajdonnison** [comment]
An email test is a good idea - although you should find that libmail will have reported any errors and you should find them in your error log.

**Comment by ajdonnison** [comment]
Test email option now available in System Admin
