### ISSUE TITLE
Project Designer throws error with php7: Parse error: syntax error, unexpected 'new' (T_NEW) in ...projectdesigner/vw_tasks.php on line 112

### ISSUE THREAD

**Issue by cleary** [dotproject/dotProject#37]
Hi Adam, 
Just testing PHP7 during this migration - project designer is giving me the following error:
Parse error: syntax error, unexpected 'new' (T_NEW) in /data/srv/debortoli.private/dotProject.git/modules/projectdesigner/vw_tasks.php on line 112

![screenshot_20181126_163020](https://user-images.githubusercontent.com/2577966/48994669-9318d000-f198-11e8-8eb5-42e7f4fcd14f.png)

It's not present with PHP5.4

**Comment by ajdonnison** [comment]
Yeah, looks like there are some assign-by-reference calls that haven't really been necessary for quite some time.  I believe removing them won't break 5 - at least from 5.3 onwards.  I'll make some changes and see if I can get that sorted out today.

**Comment by ajdonnison** [comment]
Pull from devel again - that should fix the issue.

**Comment by cleary** [comment]
That's working well - thanks
