### ISSUE TITLE
Edit Project appends visible <br /> tags to every line in the description, every time you save

### ISSUE THREAD

**Issue by cleary** [dotproject/dotProject#38]
Hi Adam, 
I'm seeing this on my test instance 
 * v2.1.9 
 * php 7.0 - I've cherry picked the commit from #37 (9b64ca3)

Every time I edit a project and hit submit, every line of the Project Description gets a <br /> tag appended - edit it a couple of times and it gets a lot of spacing, very quickly:

![screenshot_20181127_114529](https://user-images.githubusercontent.com/2577966/49050967-f1e25600-f239-11e8-82da-cf68ebdf690d.png)

![screenshot_20181127_114610](https://user-images.githubusercontent.com/2577966/49050987-09b9da00-f23a-11e8-9c8c-3c5f1a24f4ac.png)

**Comment by ajdonnison** [comment]
I've come across something similar in Tickets.  Seems that when I put in the fixes for a heap of XSS vulnerabilities, it has created a heap of formatting issues.  I'll try and get to this today.

**Comment by cleary** [comment]
Thanks!

**Comment by ajdonnison** [comment]
Just pushed a fix for this, it would be great if you could verify it works for you and doesn't break anything else.

**Comment by cleary** [comment]
I ran around and tried a bunch of similar edit fields, they all look fine - thanks again
