### ISSUE TITLE
Speed problems: suggestions for targets to focus on?

### ISSUE THREAD

**Issue by cleary** [dotproject/dotProject#39]
Hi Adam, 
We've been using our install for a long time (well over a decade?) and have amassed about 1600 projects. 

We're finding that there are certain areas in dotProject are extremely slow, where the mysqld process maxes out a cpu core, and we have to wait for significant amounts of time for a return - I assume this is by and large as a result of the sheer quantity of projects that are dealt with during a query.

Examples: 
1. Saving a task after Edit - 9-10s 
2. Clicking the Tasks module in the top menu - 80s (and only returning 13 tasks)
3. Opening a project in Project Designer module - 9-10s

Now 2) is particularly bad, but can be avoided. 1) and 3) are what are most commonly used for doing cleanup/maintenance - ie times when you just want to duck in quickly and change a few things, but after doing this a few times, waiting for the saves feels like an eternity. 

Do you have any recommendations on how/what we could do to start optimising some of these functions? 

(@mattbell87 is potentially looking for some short and sweet tasks so this may be suitable for him to work on)

I had an idea (but I'm not a db guy, so it's likely terrible) that we could move all archived projects into a completely separate table that would exclude them from having to be considered in most queries - is that a possible/feasible option?

**Comment by ajdonnison** [comment]
I think we probably need to look at the queries being generated and determining why they are slow.  It may simply be that we are missing correct indices or that we are generating overly complex queries.  My gut feeling would be that the permissions phase may be the problem - but I'd have to delve into it a bit more deeply.

If you have a staging system with the same data on it then it might be a good idea to enable slow query logging in MySQL, then we can get an idea of the exact queries causing the issue.  https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html

Alternatively if you have one that runs for a length of time you can use:
```
SHOW FULL PROCESSLIST;
```
If you do this while it is running it will show the complete query and we can take it from there.

**Comment by ajdonnison** [comment]
Looking at the code that query comes from the CTask::getAllocation method, which is run on every task - and since it is getting a user preference, even though it is the system-wide preference, it should be getting it from `$AppUI->getPref()` which pre-loads all the user preferences at login.  If it truly needs to be the system default, then we should load those in `$AppUI` as well.  Happy to commit a fix, or you can get @mattbell87 to take a look - there might also be some improvements to the rest of the queries in that function that are possible.

**Comment by cleary** [comment]
Fantastic, that particular fix is of really high value to us in the short term - it'd be great if you have an opportunity to take a look. 

For further improvements, I'm happy to pass them to Matt (he's out of commission for a few weeks though)

**Comment by ajdonnison** [comment]
Give that a go, it should remove at least part of the problem.

**Comment by cleary** [comment]
Ok I had a look at it, I'm getting the following error in most scenarios where I was previously affected (submitting Task Edits, Tasks module, Project Designer module)

`Fatal error: Uncaught Error: Call to a member function getSystemPref() on null in /data/srv/debortoli.private/dotProject.git/modules/tasks/tasks.class.php:1766 Stack trace: #0 /data/srv/debortoli.private/dotProject.git/modules/tasks/tasks.class.php(1714): CTask->getAllocation('user_id') #1 /data/srv/debortoli.private/dotProject.git/modules/tasks/do_task_aed.php(176): CTask->updateAssigned('', Array) #2 /data/srv/debortoli.private/dotProject.git/index.php(241): require('/data/srv/debor...') #3 {main} thrown in /data/srv/debortoli.private/dotProject.git/modules/tasks/tasks.class.php on line 1766`

**Comment by ajdonnison** [comment]
Sorry about that - not sure why it didn't show up in my testing - but that last push should fix that.

**Comment by cleary** [comment]
Ok, I've given it a bit of a trial - gut feeling is there's no improvement, but if I time it:
1. Saving a task after Edit - 8.32s
2. Clicking the Tasks module in the top menu - 66.73s
3. Opening a project in Project Designer module - 8.55s

So it's an improvement, but in the ~10-15% range by the looks

**Comment by ajdonnison** [comment]
Yeah, I didn't think it would be the most likely culprit.  It amazes me that saving a task would be that slow.  Do you mind running the following command from the MySQL CLI and providing the output? 
```
SHOW TABLE STATUS;
```
That will give me an idea of the size of tables and indexes involved.

**Comment by cleary** [comment]
[dp_show_status.txt](https://github.com/dotproject/dotProject/files/2626903/dp_show_status.txt)

**Comment by ajdonnison** [comment]
While none of the tables are super large by modern standards one thing that does stand out is that they are all MyISAM.  If you migrate them to InnoDB you'll see improvements in both search and update - search because a primary key lookup doesn't need to load the data (the primary key is stored with the row data, so a primary key lookup returns the data already), and because on insert/delete/update it can make use of row-level locking.  MyISAM uses table-level locks.

To do this on existing tables you need to run the following command on each table:
```
ALTER TABLE tablename ENGINE InnoDB;
```
On some of the bigger tables that is going to take some time, and you need to ensure your MySQL configuration is optimised for InnoDB - although recent versions default to that so even the base setup should be fine.

**Comment by cleary** [comment]
Alright, I've gone through that, verified each table is now using the InnoDB engine. 
I'm using a default mariadb install in CentOS 7, I don't know what that means for InnoDB optimisation, google isn't really helping me out there -

Restarted, and I'm not really seeing any improvements still 

```
[root@trevi ~]# mysql -u root -e 'show tables;' dotproject | awk '{ print $1}' | while read line; do mysql -u root -e "SHOW TABLE STATUS WHERE Name = \"$line\"" dotproject | tail -n1 | awk '{print $1 " " $2}'; done
billingcode InnoDB                                                             
common_notes InnoDB                                                             
companies InnoDB                                                                
config InnoDB                                                                  
config_list InnoDB                                                        
contacts InnoDB                                                              
custom_fields_lists InnoDB                                                       
custom_fields_option_id InnoDB                                                
custom_fields_struct InnoDB                                                   
custom_fields_struct_id InnoDB                                                 
custom_fields_values InnoDB                                                    
custom_fields_values_id InnoDB  
...
```

**Comment by ajdonnison** [comment]
That's a little disappointing.  Still, it removes yet another possible pain point.  Let's just check that we don't have index issues, can you run a `mysqldump` with the `-d` option on the dotProject database? This only puts out the create table statements, no data.  If you'd prefer, just check it against that in the `db/dotproject.sql` file from the dotProject distro and make sure all the indices are there.

If they are all there, then we need to look at what queries are being run and see if we can identify the problem that way.

With the editing of tasks taking 8+ seconds, does it matter what type of task?  If there is a difference, are there obvious differences in the task setup (e.g. one using dependencies, one not)?.

**Comment by ajdonnison** [comment]
Just looking at the table status, it looks like the entire database is less than 200MB, did you want to send me a copy privately and I'll run some tests against it here and see if I can figure out where the slowness is coming from?

**Comment by cleary** [comment]
That would be amazing, thank you

**Comment by cleary** [comment]
That'd be fantastic, thanks again

**Comment by ajdonnison** [comment]
This new push shows promise at least for the full task listing - on my system it stopped the full task list from timing out (I'm running it on a very lowly configured test server).  There looks to be room for more performance improvements in that area, but if you could run this up the flagpole and see who salutes that would be great.

**Comment by cleary** [comment]
66s -> 7s(!) for the full task listing

**Comment by ajdonnison** [comment]
A great start!  I'm sure there are more performance improvements we can get along the way.

**Comment by ajdonnison** [comment]
This push should help with saving of tasks that have a lot of dependencies and/or assignees.  This adds a change to the query class so please treat with caution and let me know of any issues.  Local testing shows it working reasonably well.

**Comment by cleary** [comment]
Thanks - I'm on leave today but will hopefully get to it Monday

**Comment by cleary** [comment]
Hi Adam, 
I just gave it a run - times are consistently 7.6s now, down from 8-9s -

**Comment by ajdonnison** [comment]
So is this the same (7.6s) for saving a task as well as for task listings?

**Comment by cleary** [comment]
...yes - I didn't notice the correlation til you mentioned it ;)

**Comment by ajdonnison** [comment]
I'm getting a lot quicker response on saving tasks - sub 2s. I note your setup is to send emails out synchronously - if you enable queuing of emails does that make a difference?

**Comment by cleary** [comment]
Ok, I've enabled the queueing for email, it doesn't make a noticeable difference here - mysqld is still using 100% of cpu for the duration of the wait too

**Comment by ajdonnison** [comment]
Interesting.  The last push should have removed the call to getAllocation from the task save, it was being called but the results weren't being used anyway.  Does it matter what type of task you are saving?  Would you perhaps have the task_id handy?  I'll make sure I'm trying to save the same task.  Also if you could run a few `SHOW PROCESSLIST;` commands in the MySQL CLI while it is at 100% CPU and let me know what sort of processes are running it might help to track down the culprit.

I've also had a few thoughts over the weekend of a generic caching mechanism that might assist in this and in permissions handling - there was some work done on that, although I think a more general approach is likely to offer better performance overall - especially if we can combine it with non-database-backed caching mechanisms (like memcached or redis, for instance).

**Comment by teodorg** [comment]
Hi guys, I just skimmed through the topic and would dedicate some time next month to join your efforts to optimize the database. Using memcached or redis is definetely a great idea, but imho lets see how much performance we can squeeze by optimizing the queries. @cleary could you provide me with a dump of your db as well?

**Comment by Givo29** [comment]
Hi @ajdonnison,

@cleary and I have recently been looking into improving the speed in certain areas of dotproject, specifically the adding/editing of tasks, which we've found can take up to 17 seconds from the time we press the save button to finish updating the task.

Upon further research of why this may be taking so long, I found the culprit query which takes around 15 seconds to complete:
```sql
SELECT u.user_id, 
CONCAT(CONCAT_WS(' [', CONCAT_WS(' ', contact_first_name, contact_last_name), 
IF(IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value) > 0, 
IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value), 0)), '%]') AS userFC, 
IFNULL(SUM(ut.perc_assignment), 0) AS charge, u.user_username, 
IFNULL(up.pref_value,100) AS chargeMax, 
IF(IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value) > 0, 
IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value), 0) AS freeCapacity 
FROM (users as u) 
LEFT JOIN contacts AS c ON c.contact_id = u.user_contact 
LEFT JOIN user_tasks AS ut ON ut.user_id = u.user_id 
LEFT JOIN user_preferences AS up ON up.pref_user = u.user_id 
GROUP BY u.user_id 
ORDER BY contact_last_name, contact_first_name;
```
This query is called in the `getAllocation` function in `tasks.class.php`. We (with help from @benletchford) have managed to optimise the query to the point where it runs in less than a second:
```sql
SELECT 
u.user_id, 
CONCAT(CONCAT_WS(' [', CONCAT_WS(' ', contact_first_name, contact_last_name), 
IF(IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value) > 0, 
IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value), 0)), '%]') AS userFC, 
IFNULL(SUM(ut.perc_assignment), 0) AS charge, u.user_username, 
IFNULL(up.pref_value,100) AS chargeMax, 
IF(IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value) > 0, 
IFNULL((IFNULL(up.pref_value, 100) - SUM(ut.perc_assignment)), up.pref_value), 0) AS freeCapacity 
FROM (users as u) 
LEFT JOIN (SELECT * FROM contacts GROUP BY contact_id) AS c ON c.contact_id = u.user_contact 
LEFT JOIN (SELECT user_id, user_type, task_id, SUM(perc_assignment) AS 'perc_assignment', user_task_priority FROM user_tasks GROUP BY user_id) AS ut ON ut.user_id = u.user_id 
LEFT JOIN user_preferences AS up ON up.pref_user = u.user_id 
GROUP BY u.user_id
ORDER BY contact_last_name, contact_first_name, u.user_id;
```
But we are having trouble implementing it using the query class due to having select queries inside our left joins. This would take me a while to get going as I'd have to familiarise myself with how the query class works, would this be something you could do quickly and/or easily?

**Comment by ajdonnison** [comment]
Sure, I'll take a look @Givo29

**Comment by cleary** [comment]
Hi @ajdonnison - thanks for offering to take a look.

Do you have any timeline on when you'll be able to check it out? 

It's extremely high value for our users - so I'm just trying to work out the fastest/most efficient path to completion.

**Comment by ajdonnison** [comment]
@cleary I've just got back from a trip to the USA, which is why I've been a bit tardy in responding. At first glance I'd say there is a bit of work required but it may be possible by passing a pointer to another DBQuery instance in as an argument to the join - probably capable of doing that relatively easily with changes to the query generator and the query preparer parts.  Let me take a look in the morning and get back to you on the proposed amount of work and time.

**Comment by cleary** [comment]
G'day Adam, 
Welcome home - thanks a lot :)

**Comment by ajdonnison** [comment]
@cleary @Givo29 I've just pushed a change to the devel branch that adds  supports for sub-selects as tables for joins.  You can do something like:
```php
$q = new DBQuery;
$subq = new DBQuery;
$subq->addTable('subselectedTable');
$q->addTable('mainTable', 'm');
$q->addJoin($subq, 'a', 'm.id = a.subId');
$q->exec();
```

**Comment by cleary** [comment]
Thanks Adam! Joel is back in on Thursday, I'll get him to give it a crack then :)
