### ISSUE TITLE
Wrong expected duration calculation

### ISSUE THREAD

**Issue by BachirCoder** [dotproject/dotProject#42]
There is this calculation error. After I specify the starting/ending date and time for a given task, I click on "Duration" button. I get wrong calculated duration. The erroneous calculation happens only when calculating hours. The calculation is correct for days but not hours. I am not sure whether there an inherent mistake in the code or my configurations are wrong.
Please see the attached picture. The duration in the photo should be 4 hours and not 10 hours!
I hope there is a solution for this as there are some tasks that span across days.
Thank you.

![dotp issue](https://user-images.githubusercontent.com/11787680/49807718-b1fb9280-fd52-11e8-8c2d-20f500294a0d.jpg)

**Comment by ajdonnison** [comment]
As per @jman1ac there is no error as you have it starting at 08:30 on one day and completing 10:30 the following, which is 8 hours (1 day) + 2 hours = 10 hours.
