### ISSUE TITLE
Commercial support link dead, have a question?

### ISSUE THREAD

**Issue by Biggly** [dotproject/dotProject#43]
Hi, am trying to evaluate the software. The wiki is blank and the support link is dead, so really not sure where else to ask my primary question?

Here's the question - as a freelancer, I work with multiple companies. What I want to do, need to do, is create a template for new clients, so the milestones and task lists can be easily copied for a new client.

At that point, I need to ensure the new client does NOT see any details of the projects for older clients, likewise I need to ensure older clients CANNOT see any details about newer clients and their projects.

I've found a "Make private entry" for contacts, but what does that do? I really don't want clients seeing each other's email addresses or details.

If I assign a project to a company, does that mean no 'contacts' can see that project, unless they are also assigned to the correct 'company'?

Thanks!

**Comment by ajdonnison** [comment]
By default no permission is available to anyone.  A user must be assigned a role that gives them a certain level of permission to access.  The default setup has a number of pre-defined roles that allow for various levels of access.  When you add a user, you assign a role to them, then you can also assign individual permissions.  So, in your case you could create roles that are tied to the companies you want to work with, and when you create users in those companies assign the associated company role.  The role (in System Admin -> User Roles) should limit the access to the Companies module based on the company in question.  If that is set then anything not associated with that company (projects, tasks, contacts, etc) will not be available to someone who has *just that role* assigned.

**Comment by ajdonnison** [comment]
As to where to ask questions, you've come to the right place.  The wiki will be progressively built out over the next few months.  We are in a state of transition and things will take a bit of time to settle in.  Thanks for your patience.
