### ISSUE TITLE
Handling of project costs

### ISSUE THREAD

**Issue by 73erln91** [dotproject/dotProject#44]
First of all: thanks for developing and maintaining this nice software.
Perhaps the issue of project costs is covered by the wiki but wiki is currently not available.
I can not find out how to properly manage and control project costs - I can only see the budget of hours.
My questions:
System Administration - Billing Code Table: What is a "Billing Code" and which meaning has the associated "Value"? Is it the hourly rate?
TaskLogs: What is the "Cost Code" and what is the value after "->"? I would expect it to be the "Value" from above but in my case a strange non-related is being taken here.
General: Where are the project costs (i.e. hours x hourly rates) being evaluated? I only find the total sum of hours. From my point of view the project costs and financial budget are of primary importance, not hours? Moreover - if there are different hourly rates of involved people, the total time is meaningless.
Why can I enter the project financial budget when there is no evaluation of the corresponding running project costs there?
Am I missing something?

**Comment by teodorg** [comment]
Ok, as a start I would like to elaborate that I am not one of the developers of the software. So, bear that in mind. In my humble opinion, the billing code feature is unfinished.  I came to this conclusion whilst browsing through the code. You can define various billing codes (separated by company), assigned them codenames, values and description. Then in task updates you can assign a billing code to each task. And that is all. The billing code value (which imho is supposed to be the cost of a particular service) is used nowhere. It is mentioned in the "overall report" page at the projects module, but the code is commented. 

Probably the idea of the author was to use it as a quick and easy way to add and bill the user for a predefined set of services (like "technicians visit - $50", "sending a printed manual - $20", "generating a report" - $10). Then you just choose and apply the code to a specific task.

But, as I said above - it seems like an unifished feature.
