### ISSUE TITLE
report pdf

### ISSUE THREAD

**Issue by fatabek** [dotproject/dotProject#47]
In /lib/ezpdf/fonts/ files named "Helvetica.afm" and "Helvetica-Bold.afm", but dotproject search "php_Helvetica.afm" and   "php_Helvetica-Bold.afm" therefore I changed files name. But
 in this case pdf files like this : 

![err02](https://user-images.githubusercontent.com/41823969/50842704-4ff57380-1378-11e9-85cc-c8430326096d.JPG)

or like this:

![err01](https://user-images.githubusercontent.com/41823969/50842722-58e64500-1378-11e9-9a0a-6fc5323e3e62.JPG)

**Comment by ajdonnison** [comment]
The php_* files are the source files, you just need to make that directory writable and the system will create the required .afm files.
