### ISSUE TITLE
PHP7 MySQL Support Not available

### ISSUE THREAD

**Issue by 8mccm8** [dotproject/dotProject#5]
Hi all,
it's look like mysql_* function is déprecated with PHP7
add we should use mysqli_*

Can you confirm?

[Wed Dec 06 12:10:50.770901 2017] [:error] [pid 11919] [client 127.0.0.1:60878] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/prj/lib/adodb/drivers/adodb-mysql.inc.php:363\nStack trace:\n#0 /var/www/html/prj/lib/adodb/adodb.inc.php(525): ADODB_mysql->_connect('localhost', 'prj', 'prj', '')\n#1 /var/www/html/prj/install/do_install_db.php(62): ADOConnection->Connect('localhost', 'prj', 'prj')\n#2 {main}\n  thrown in /var/www/html/prj/lib/adodb/drivers/adodb-mysql.inc.php on line 363, referer: http://127.0.0.1/prj/install/db.php

root@taff:/var/www/html/prj# dpkg -l | grep mysql
ii  libdbd-mysql-perl                                           4.041-2                                        amd64        Perl5 database interface to the MariaDB/MySQL database
ii  mysql-common                                                5.8+1.0.2                                      all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  php-mdb2-driver-mysql                                       1.5.0b4-2                                      all          mysql MDB2 driver
ii  php-mysql                                                   1:7.0+49                                       all          MySQL module for PHP [default]
ii  php7.0-mysql                                                7.0.19-1                                       amd64        MySQL module for PHP

root@taff:/var/www/html/prj# mysql -uprj -pprj
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1
Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MariaDB [(none)]>

**Comment by ajdonnison** [comment]
Yes, the mysql extension was removed in PHP 7, there is only the PDO_mysql and mysqli.  Note that we use the ADOdb abstraction layer, which will probably also need to be updated.  http://adodb.org/dokuwiki/doku.php
It can run with any supported driver and the latest version runs on PHP 7

**Comment by mattbell87** [comment]
@ajdonnison how's this going? I'm in the De Bortoli Wines org, I can give it a crack.

I can't actually install this on my laptop at the moment. My distro only ships with 7, so that should be a good test!

**Comment by ajdonnison** [comment]
Just to let you know, the devel branch fixes this issue
