### ISSUE TITLE
priority+1.gif broken in Projects priority P

### ISSUE THREAD

**Issue by bsandersKG** [dotproject/dotProject#52]
The priority+1.gif is broken in the P column of projects screen
![image](https://user-images.githubusercontent.com/47598335/52712471-443e3380-2f5a-11e9-8ecb-ab494b5afeeb.png)

**Comment by ajdonnison** [comment]
I can't duplicate the issue, can you provide some information on the system setup?  What OS, web server, web browser, etc?

**Comment by bsandersKG** [comment]
dotProject was installed on GoDaddy The OS on the workstation is Windows 10, the browser is Chrome
In testing I created a  file on GoDaddy, who  is the host,  with a + in name and it was no longer reachable. It is like it does not like a plus in the name and renders the file unusable, can’t rename , can’t delete it,  nor access it in any way. The  priority+1.gif file is the same on the GoDaddy web host. Can’t access it, use it, delete it nor rename it
 Here is the link and password where you can see for yourself
login: dphelp
pw" 123456789
Link" http://go2tek.biz/dotproject/

**Comment by bsandersKG** [comment]
go to the existing project or create one of your own it is a test site

**Comment by bsandersKG** [comment]
Actually if you can tell me which php file to edit to change the name of the file I can upload a new .jpg and rename the image file in the php code. I realize if it upgrades I might have to do it again

**Comment by ajdonnison** [comment]
I've just pushed a fix for this.
