### ISSUE TITLE
After install,there is a session error

### ISSUE THREAD

**Issue by coollyr** [dotproject/dotProject#54]
after i install,there is a session error like this:
![image](https://user-images.githubusercontent.com/47944345/53300109-bd545980-387d-11e9-9d3e-95735a336738.png)

**Comment by coollyr** [comment]
My environment：Windows 10 64-bit，xampp（7.3.2）。Thanks 。

**Comment by ajdonnison** [comment]
I believe you may be using the master branch which has a known problem with 7.x  - try using the devel branch: https://github.com/dotproject/dotProject/archive/devel.zip

**Comment by coollyr** [comment]
@ajdonnison thanks a lot. I switch to devel branch ,and I can login。But there is a another question:if I set session.auto_start=0 in 'php.ini'，I can't login;if I set session.auto_start=1,there still appear a warn like this:
![image](https://user-images.githubusercontent.com/47944345/53313297-b5cf9780-38f3-11e9-8af3-2e893b195812.png)

**Comment by ajdonnison** [comment]
@coollyr we have seen some recent activity that suggests that this value depends on the backend webserver you are using. XAMPP uses Apache, and I have seen that this does require session.auto_start, while I use Nginx with FPM and this doesn't appear to require that.   I'll keep looking to see if there is a workaround for Apache.

**Comment by coollyr** [comment]
@ajdonnison OK，I switch to dotproject2.1.8 and make wamp as web server，it seems ok.Thank .
