### ISSUE TITLE
Column 'task_id' in where clause is ambiguous

### ISSUE THREAD

**Issue by tjq99tjq** [dotproject/dotProject#58]
Hi，
When set deny role for task，Display the following error。
ERROR: C:\xampp\htdocs\meipeng\includes\db_adodb.php(69): Error executing: SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date (Column 'task_id' in where clause is ambiguous) Backtrace: 0 C:\xampp\htdocs\meipeng\includes\db_adodb.php:69 dprint('C:\\xampp\\htdocs\\meipeng\\includes\\db_adodb.php',69,0,'Error executing: SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date (Column \'task_id\' in where clause is ambiguous)') 1 C:\xampp\htdocs\meipeng\modules\tasks\tasks.php:316 db_exec('SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date') 2 C:\xampp\htdocs\meipeng\style\default\overrides.php:95 require('C:\\xampp\\htdocs\\meipeng\\modules\\tasks\\tasks.php') 3 C:\xampp\htdocs\meipeng\modules\projects\view.php:481 show() 4 C:\xampp\htdocs\meipeng\index.php:301 require('C:\\xampp\\htdocs\\meipeng\\modules\\projects\\view.php') <\pre> Column 'task_id' in where clause is ambiguous | ERROR: C:\xampp\htdocs\meipeng\includes\db_adodb.php(69): Error executing: SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date (Column 'task_id' in where clause is ambiguous) Backtrace: 0 C:\xampp\htdocs\meipeng\includes\db_adodb.php:69 dprint('C:\\xampp\\htdocs\\meipeng\\includes\\db_adodb.php',69,0,'Error executing: SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date (Column \'task_id\' in where clause is ambiguous)') 1 C:\xampp\htdocs\meipeng\modules\tasks\tasks.php:316 db_exec('SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date') 2 C:\xampp\htdocs\meipeng\style\default\overrides.php:95 require('C:\\xampp\\htdocs\\meipeng\\modules\\tasks\\tasks.php') 3 C:\xampp\htdocs\meipeng\modules\projects\view.php:481 show() 4 C:\xampp\htdocs\meipeng\index.php:301 require('C:\\xampp\\htdocs\\meipeng\\modules\\projects\\view.php') <\pre> Column 'task_id' in where clause is ambiguous
-- | --
ERROR: C:\xampp\htdocs\meipeng\includes\db_adodb.php(69): Error executing: SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date (Column 'task_id' in where clause is ambiguous) Backtrace: 0 C:\xampp\htdocs\meipeng\includes\db_adodb.php:69 dprint('C:\\xampp\\htdocs\\meipeng\\includes\\db_adodb.php',69,0,'Error executing: SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date (Column \'task_id\' in where clause is ambiguous)') 1 C:\xampp\htdocs\meipeng\modules\tasks\tasks.php:316 db_exec('SELECT distinct tsk.task_id, task_parent, task_name, task_start_date, task_end_date, task_dynamic, task_pinned, pin.user_id as pin_user, task_priority, task_percent_complete, task_duration, task_duration_type, task_project, task_description, task_owner, task_status, usernames.user_username, usernames.user_id, task_milestone, assignees.user_username as assignee_username, count(distinct assignees.user_id) as assignee_count, co.contact_first_name, co.contact_last_name, count(distinct fi.file_task) as file_count, if (tlog.task_log_problem IS NULL, 0, tlog.task_log_problem) AS task_log_problem FROM (dotp_tasks as tsk) LEFT JOIN dotp_projects as prj ON project_id = task_project LEFT JOIN dotp_users as usernames ON task_owner = usernames.user_id LEFT JOIN dotp_user_tasks as ut ON ut.task_id = tsk.task_id LEFT JOIN dotp_users as assignees ON assignees.user_id = ut.user_id LEFT JOIN dotp_contacts as co ON co.contact_id = usernames.user_contact LEFT JOIN dotp_task_log AS tlog ON tlog.task_log_task = tsk.task_id AND tlog.task_log_problem > 0 LEFT JOIN dotp_files as fi on tsk.task_id = fi.file_task LEFT JOIN dotp_user_task_pin as pin ON tsk.task_id = pin.task_id AND pin.user_id = 52 WHERE  task_project = 27 AND task_status = 0 AND project_company IN (1) AND task_id NOT IN (616) AND task_parent NOT IN (616) GROUP BY task_id ORDER BY project_id, task_start_date') 2 C:\xampp\htdocs\meipeng\style\default\overrides.php:95 require('C:\\xampp\\htdocs\\meipeng\\modules\\tasks\\tasks.php') 3 C:\xampp\htdocs\meipeng\modules\projects\view.php:481 show() 4 C:\xampp\htdocs\meipeng\index.php:301 require('C:\\xampp\\htdocs\\meipeng\\modules\\projects\\view.php') <\pre> Column 'task_id' in where clause is ambiguous

**Comment by ajdonnison** [comment]
Can you verify what version of dotProject you are using?  The line numbers don't match up with what I'd expect.

**Comment by ajdonnison** [comment]
This should now be fixed in the latest devel branch

**Comment by pannonius** [comment]
1. Warning: Illegal string offset 'where' in /usr/local/www/apache24/data/klijenti/modules/projects/projects.class.php on line 303
2. Warning: Illegal string offset 'from' in /usr/local/www/apache24/data/klijenti/classes/dp.class.php on line 382

ERROR: /usr/local/www/apache24/data/klijenti/classes/query.class.php(636): query failed(SELECT project_id,project_name FROM (`dotp_projects`,`dotp_(`) ORDER BY project_name) - error was: Table 'dotproject.dotp_(' doesn't exist
Backtrace:
0 /usr/local/www/apache24/data/klijenti/classes/query.class.php:636 dprint('/usr/local/www/apache24/data/klijenti/classes/query.class.php',636,0,'query failed(SELECT project_id,project_name FROM (`dotp_projects`,`dotp_(`) ORDER BY project_name) - error was: Table \'dotproject.dotp_(\' doesn\'t exist')
1 /usr/local/www/apache24/data/klijenti/classes/query.class.php:679 exec(2)
2 /usr/local/www/apache24/data/klijenti/classes/dp.class.php:399 loadHashList(NULL)
3 /usr/local/www/apache24/data/klijenti/modules/projects/projects.class.php:306 getAllowedRecords(1,'project_id,project_name','project_name',NULL,'(')
4 /usr/local/www/apache24/data/klijenti/modules/files/folders_table.php:947 getAllowedRecords('1','project_id,project_name','project_name',NULL,'(')
5 /usr/local/www/apache24/data/klijenti/style/default/overrides.php:95 require('/usr/local/www/apache24/data/klijenti/modules/files/folders_table.php')
6 /usr/local/www/apache24/data/klijenti/modules/files/index.php:95 show()
7 /usr/local/www/apache24/data/klijenti/index.php:301 require('/usr/local/www/apache24/data/klijenti/modules/files/index.php')
Table 'dotproject.dotp_(' doesn't exist
