### ISSUE TITLE
set_magic_quotes_runtime

### ISSUE THREAD

**Issue by 8mccm8** [dotproject/dotProject#6]
hi 
Warning
This function was DEPRECATED in PHP 5.3.0, and REMOVED as of PHP 7.0.0.
[Wed Dec 06 12:23:15.842030 2017] [:error] [pid 11919] [client 127.0.0.1:32840] PHP Fatal error:  Uncaught Error: Call to undefined function set_magic_quotes_runtime() in /var/www/html/prj/install/install.inc.php:146\nStack trace:\n#0 /var/www/html/prj/install/do_install_db.php(161): InstallLoadSql('/var/www/html/p...')\n#1 {main}\n  thrown in /var/www/html/prj/install/install.inc.php on line 146, referer: http://127.0.0.1/prj/install/db.php

**Comment by ajdonnison** [comment]
Probably safe to remove as of PHP 5, but we will need to check as a lot depends on it.

**Comment by patredmond** [comment]
Should be fairly easy to skip "set_magic_quotes_runtime()" for PHP after 5.3.0 - see patch below. Note that the patch has a bit of noise - there seem to be a variety of line endings which Sublime doesn't really like.
This patch creates issues for me in PHP 7.0.3, which seems to be related to https://github.com/dotproject/dotProject/issues/5

[set_magic_quotes_runtime.patch.txt](https://github.com/dotproject/dotProject/files/1598992/set_magic_quotes_runtime.patch.txt)

**Comment by ajdonnison** [comment]
Not 100% sure, I'll check it again, but I believe the recent changes I made to the `devel` branch fixes this.

**Comment by ajdonnison** [comment]
This is resolved
