### ISSUE TITLE
Parse error:  syntax error, unexpected T_FUNCTION in /webs

### ISSUE THREAD

**Issue by epiclolzhere** [dotproject/dotProject#69]
I am trying a new install of dotProject

Version 2.1.9

When installing I seem to have all the green ticks on the pre-install check. However once I have entered my database info I get the following:

Progress:
--
Installing database There were 0 errors in 211 SQL statements  Parse error:  syntax error, unexpected T_FUNCTION in /websites/123reg/LinuxPackage22/ol/iv/er/olivermartinhosting.co.uk/public_html/projects.olimartin.com/includes/filter.php on line 308

**Comment by Givo29** [comment]
@epiclolzhere The line you're referring to in `inlcudes/filter.php` is an anonymous function, which are only supported from php version 5.3 and higher, so it seems like it could be a compatibility issue with the php version you're using. Try upgrading your php version to at least php 5.3 and run it again.

[Extra information - related issue](https://stackoverflow.com/questions/3657357/unexpected-t-function-error-when-using-function-array-matches)

**Comment by epiclolzhere** [comment]
This fixed it, thank you!
