### ISSUE TITLE
Migrate Database: Safest way

### ISSUE THREAD

**Issue by pedrohenriquerissato** [dotproject/dotProject#77]
Hello!

I need to migrate the dotProject database from host, ie.: .100 to .175, but since i'm not suppose to manually edit config-dist.php ou config.php, what is the correct way of doing this, without deleting/erasing the actual database on .100? I'm afraid pointing out to /install and the scripts ends up deleting my populated database.

**Comment by Givo29** [comment]
Hi,
On the new host you should be able to go through the install normally without it affecting the database on the old host. This should create a blank database on the new host, ideally with the same name and permissions as on old host.

On the old host, take a `mysqldump` if you don't already have one and bring it over to the new host.

From here on the new host you should be able to run a command like:
```
mysql -u username -p database_name < dump_file.sql
```
and the new database will be populated with all your old data.

**Comment by pedrohenriquerissato** [comment]
Hi Givo, thank you for the quick answer. But I don't want to migrate the hole application, just migrate the database. The application (php/apache server) will remain on server .100, for ie., and only the database I need to migrate to another server where all other MySQL databases are. The problem is about edint manually those config files on /include. Besides the warning about not to do it manually, could I? Is there any side effect of doing it?

**Comment by Givo29** [comment]
Ok I understand. You should be able to edit any files you need to without any side effects. You can always revert your changes with git in case something does happen, and if you take an sqldump of all your data before hand you will be fine.

**Comment by pedrohenriquerissato** [comment]
Thank you Givo.

Made a full backup of database (parameters are optional):
`mysqldump -u USER -p DATABASE --single-transaction --quick --lock-tables > FILENAME`

Created the database users manually. Gave permissions and flush privileges on the new database server.

Then, modified ../include/config.php from dotproject folder:
`$dPconfig['dbhost'] = 'NEW IP'`
* IP without port: 0.0.0.0

Saved config.php and that's it. Everthing works flawless! :)
