### ISSUE TITLE
Call to undefined function utf8_decode() (php-xml)

### ISSUE THREAD

**Issue by mattbell87** [dotproject/dotProject#78]
Installing dotProject on my rPi and I just noticed that without php-xml installed if you call utf8_decode you get a fatal error:

> Fatal error: Uncaught Error: Call to undefined function utf8_decode() in 
> /var/www/html/dotProject/modules/tasks/do_updatetask.php:15 Stack trace: \#0 
> /var/www/html/dotProject/modules/tasks/do_updatetask.php(75): cleanText('') \#1
> /var/www/html/dotProject/index.php(241): require('/var/www/html/d...') \#2 {main}
> thrown in /var/www/html/dotProject/modules/tasks/do_updatetask.php on line 15

I ran `sudo apt install php-xml` and it immediately fixed the problem.

A check should be added to the install script for php-xml.

**Comment by ajdonnison** [comment]
From PHP 7.2.0 utf8_decode was moved to core.  Can you tell me what version of PHP you are using?

**Comment by mattbell87** [comment]
That was a while ago now and I've rebuilt the rpi and moved dotproject to a Docker container. Since it was running on a fork of Debian (Raspbian) there's a good chance it was running on an older version of PHP.

**Comment by ajdonnison** [comment]
Added a check, wrongly attributed to another issue (#17)
