### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by nishadsshinde** [dotproject/dotProject#79]
hi,

i am getting following error after installing dotproject.

Progress:
Creating new Database
Installing database
There were 0 errors in 211 SQL statements
( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; gacl has a deprecated constructor in
C :\wamp64\www\dotProject\lib\phpgacl\gacl.class.php on line 43
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 8.1130 774656 require_once( 'C :\wamp64\www\dotProject\classes\permissions.class.php' ) ...\upgrade_permissions.php:20
Creating new Permissions objects
( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; C ache_Lite has a deprecated constructor in
C :\wamp64\www\dotProject\lib\phpgacl\C ache_Lite\C ache_Lite.php on line 21
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 8.1270 853152 dPacl->__construct( ) ...\upgrade_permissions.php:23
4 8.1270 855224 dPacl->gacl( ) ...\permissions.class.php:70
5 8.1570 858656 require_once( 'C :\wamp64\www\dotProject\lib\phpgacl\C ache_Lite\Hashed_C ache_Lite.php' ) ...\gacl.class.php:133
( ! ) Deprecated: The each() function is deprecated. This message will be suppressed on further calls in
C :\wamp64\www\dotProject\lib\phpgacl\C ache_Lite\C ache_Lite.php on line 152
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 8.1270 853152 dPacl->__construct( ) ...\upgrade_permissions.php:23
4 8.1270 855224 dPacl->gacl( ) ...\permissions.class.php:70
5 8.1600 861584 Hashed_C ache_Lite->C ache_Lite( ) ...\gacl.class.php:148
6 8.1600 861608 each ( ) ...\C ache_Lite.php:152
( ! ) Notice: Only variables should be assigned by reference in C :\wamp64\www\dotProject\lib\phpgacl\gacl_api.class.php on line 966
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 9.0420 863720 dPacl->add_acl( ) ...\upgrade_permissions.php:152
( ! ) Notice: Array to string conversion in C :\wamp64\www\dotProject\lib\phpgacl\gacl_api.class.php on line 954
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 9.0420 863720 dPacl->add_acl( ) ...\upgrade_permissions.php:152
( ! ) Notice: Only variables should be assigned by reference in C :\wamp64\www\dotProject\lib\phpgacl\gacl_api.class.php on line 966
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 9.0420 863720 dPacl->add_acl( ) ...\upgrade_permissions.php:152
( ! ) Notice: Only variables should be assigned by reference in C :\wamp64\www\dotProject\lib\phpgacl\gacl_api.class.php on line 999
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 9.0420 863720 dPacl->add_acl( ) ...\upgrade_permissions.php:152
( ! ) Notice: Only variables should be assigned by reference in C :\wamp64\www\dotProject\lib\phpgacl\gacl_api.class.php on line 999
C all Stack
# Time Memory Function Location
1 0.0020 408680 {main}( ) ...\do_install_db.php:0
7/2/2019 dotProject Installer
localhost:8085/dotproject/install/do_install_db.php 14/14
2 8.0840 627904 include_once( 'C :\wamp64\www\dotProject\db\upgrade_permissions.php' ) ...\do_install_db.php:190
3 9.0420 863720 dPacl->add_acl( ) ...\upgrade_permissions.php:152
Converting admin user permissions to Administrator Role
Searching for add-on modules to add to new permissions
Updating version information
Creating config
Database Installation Feedback: Database successfully setup
Config File Creation Feedback: Config file written successfully
Login and Configure the dotProject System Environment
The Administrator login has been set to admin with a password of passwd. It is a good idea to change this password when you first log

**Comment by Givo29** [comment]
Hi, 
The bottom block makes it seem as though the install worked and I can't see any errors besides deprecation warnings, are you sure it didn't work?

**Comment by nishadsshinde** [comment]
Hi

Thanks for the update after commenting out the line 195 in session.php,
The warnings still came but the login screen came.
