### ISSUE TITLE
can no longer log in on fresh install of dotProject

### ISSUE THREAD

**Issue by SadBaxter** [dotproject/dotProject#89]
Hi,

I've got an issue where dotProject seems to have lost the ability to successfully log in overnight.

I was able to install and use dotProject multiple times yesterday with no issues. Today I went and downloaded a new .zip from the devel branch (stupidly overwriting the old one) and any new instance of dotProject I create cannot log in. Entering a bad login doesn't cause the "login failed" text to show up.

Not sure what's happened. There's nothing on the site that would indicate anything's changed but I swear I'm not doing anything differently to what I did the day before.

**Comment by cleary** [comment]
Try migrating your database by going to:

> <your ip or hostname>[:<optional port>]/install/

Example:

> http://192.168.1.1/install

**Comment by SadBaxter** [comment]
Trying to use install.php to change a dotproject install to a new db has interesting results. Whole reason I've been playing around with multiple installs is to migrate over a database from an older version to the newer one, which I did manage to get working yesterday and still works today.
 
Tried copying the working dotProject install into a new folder, removing config.php from /includes, and doing install from new db (drop existing table etc.): bug happens

Copied working install into new folder, made identical copy of working install's database, tried doing install where it writes to config only: bug happens

Copied working install into new folder, identical copy of DB, install where it writes to DB and config without dropping table: everything explodes, fatal php error

Tried using new install from .zip, copied DB from working install: same results as above no matter what.

Also tried copying working install and changing the dbname variable in config.php to point to a copied db, which caused the whole thing to not work due to php errors. Probably need to try more than that.

if I could clone this working dotProject thing then I could test that directly, I don't want to try copying in a new db and having it also stop working.

**Comment by cleary** [comment]
I'm not going to be able to offer much assistance from here, but here's some tips from my experience doing the same:

1. Don't try and migrate to the devel branch - it is precisely that, in development
2. Migrate to master first (which is the 2.1.9 release), and verify it's working
3. If there are features that you like/want in the devel branch, make your own fork from master, cherry-pick those feature commits and test test test

[This fork](https://github.com/DeBortoliWines/dotProject?organization=DeBortoliWines&organization=DeBortoliWines) is an example of that process in action, it works in our production environment - I can't guarantee it for anyone else

**Comment by SadBaxter** [comment]
There were a bunch of issues with the master branch, particularly with bringing across the existing db. The devel one worked perfectly and had no issues with importing yesterday which is why the bossman wanted to switch to it.

As far as doing my own fork, that's the eventual goal but I know very little about sql or php, big part of this job is me learning as I go and this was meant to just be a simple swap like for like kinda thing.

I'll keep playing around until it works I guess, or give the master branch another try.

**Comment by SadBaxter** [comment]
I figured that maybe something was wrong with index.php because that's where the "login failed" message should be coming up, and found that dotProject _is_ creating user access log records on good logins. They just have an IP address of "::1" and "0000-00-00 00:00:00" for time out/last action.

**Comment by cleary** [comment]
[::1 indicates localhost in ipv6 address notation (shorthand) ](https://superuser.com/questions/668004/why-is-my-localhost-not-127-0-0-1-but-1-and-what-notation-is-that) - I don't know how that would affect dotproject, if at all. The webserver should abstract that part away fine

I suspect you may need to confirm your time and date settings on the new server though (and potentially the old one too, if you need to change it significantly, dump your database from that server again)

**Comment by SadBaxter** [comment]
Yeah I did check and the access logs on the working dotProject also was doing the ipv6 address, once I found the right ones. Logins are also creating entries in the "sessions" table even if I can't go beyond the login page, for whatever reason.

**Comment by SadBaxter** [comment]
Okay, setting session.auto_start = 1 allows me to log in, although it causes a php error to float at the top of the screen constantly about not being able to rename an active session. Turning auto start off causes the login problem to resurface again. 
The working install doesn't need auto start on to log in, and it gets the same php error about naming active session while it's on.

Is this the kinda thing that would let someone know what's happening? Also is it safe to just comment out the session_name part of session.php and keep auto start on?

**Comment by Givo29** [comment]
> Tried copying the working dotProject install into a new folder, removing config.php from /includes, and doing install from new db (drop existing table etc.): bug happens
> 
> Copied working install into new folder, made identical copy of working install's database, tried doing install where it writes to config only: bug happens
> 
Does php give you an error when you try to login or does nothing happen?
Does the browser developer console tell you anything useful? If so, can you please supply screenshots?
> Copied working install into new folder, identical copy of DB, install where it writes to DB and config without dropping table: everything explodes, fatal php error
> 
> Tried using new install from .zip, copied DB from working install: same results as above no matter what.
> 
> Also tried copying working install and changing the dbname variable in config.php to point to a copied db, which caused the whole thing to not work due to php errors. Probably need to try more than that.
> 
Can you please send a screenshot of the php errors you're seeing? If we see the errors it would be much easier for us to help you.

**Comment by SadBaxter** [comment]
Okay i was going to write a long post detailing all the stuff I was doing to try and figure this out but I had a breakthrough.

I eventually discovered that I could swap the file directory for that virtualhost and its instance would start working, it was the name it got not the files themselves. Started looking at cookies in firefox's storage inspector.

https://i.imgur.com/D74snFr.png
For the working site, they're updating two cookies named dotproject and PHPSESSID respectively, with values that are long sequences of letters and numbers, probably session ID stuff.

For the non-working sites, those session IDs are being put in the name field instead, their value is set as "value" https://i.imgur.com/D74snFr.png

I don't know how to fix this at all but I guess I can have a poke around tomorrow.

As an aside, Here's the contents of what's on the do_install.php page after doing an install on a new DB as well https://pastebin.com/Sj21jnp3 There's a lot of errors but most of them seem to be about deprecated methods or being used incorrectly. The server I'm using is running php 7.2.18, is there a version dotproject behaves better with currently?

**Comment by SadBaxter** [comment]
I found the issue at last, it's related to a combination of how I was virtually hosting dotproject's URL and how session.php handles URLs.

Line 210 to 222 in session.php is where it all goes wrong but I don't understand the exact things that are happening, basically:
- My dotproject is virtualhosted on port 80
- Browser scrubs the :80 at the end of the url
- session.php keeps the :80 at the end of the domain
- this is then parsed into session_set_cookie_params and will cause the session cookie to have the wrong domain forever.

I also did a search and found that apparently this was an issue multiple other people had, and it escaped being solved somehow (issues #54 and #60) because people solved this problem by turning session.auto_start to on (which caused another php error)

Manually setting $domain to have the correct bit of the URL fixes everything but this probably needs a better solution which I'll do some research into myself. I think it's probably down to how firefox scrubs :80 from the url, and if it was hosted on a different port and kept that in the URL things would be fine.

**Comment by ajdonnison** [comment]
@SadBaxter thanks for the excellent detective work.  I'll take a look tonight and fix this.  Now I know where the issue is it should be relatively straightforward.

**Comment by SadBaxter** [comment]
I've been scratching my head for days over this and I know literally nothing about php or anything, felt like I was banging rocks together the whole time. Never would have gotten on the right path to finding out out if @Givo29 hadn't suggested looking at the browser developer console neither.

Fix would be very welcome although I'm fairly certain it'll only ever show up on certain browser/port combinations.

**Comment by ajdonnison** [comment]
@SadBaxter the fix I just pushed should resolve the issue.  The regex that was pulling apart the URL for generating the cookie was wrong.  Fixing that has resolved the issue, at least in my testing.  Thanks again for the pointer.

**Comment by ajdonnison** [comment]
One more change, I'd left in some debug.  Should be fine now.

**Comment by SadBaxter** [comment]
Working perfectly, thank you so much.
