### ISSUE TITLE
Problemas varios

### ISSUE THREAD

**Issue by gustavo20010** [dotproject/dotProject#92]
Good I am new to this, my English is bad but I will do my best to understand what I add.
I was using dotproject for 2 years and everything was fine, but two weeks ago in a project -> homework ... when I edit, I make changes and at the time of saving, it doesn't save it and I have to do this two or three times and it ends saving
Another one that happens to me also does it when I want to delete a project. It does the same, it does not delete it and I must try several times.
I hope to see how to solve this or if it is a configuration that may have changed

Thank you

Gustavo from Argentina

dejo dos links de videos donde se ve esto 
http://www.sercomnet.com/back/dot-1.mp4
http://www.sercomnet.com/back/dot-2.mp4

**Comment by ajdonnison** [comment]
You might want to check that there are no problems in the database.  If you are running on your own server then you can use `mysqlcheck -A --auto-repair` - if not you may want to check with your hosting provider if they have a similar option.

**Comment by gustavo20010** [comment]
thanks for answering. I found that on the server of my hosting they had implemented a different type of cache and that was why it worked badly. Thank you
