### ISSUE TITLE
dotProject. First time.  I have already stumbled into the Admin / passwd problem.

### ISSUE THREAD

**Issue by jalgan** [dotproject/dotProject#96]
I refer to the same problem # 13 by it19862 ajdonnison closed this on 28 Apr: "What login and password should I enter after installation?"

Apache logerror says:
[Wed Oct 09 00: 00: 48.236481 2019] [php7: warn] [pid 3404: tid 792] [client 127.0.0.1:49950]
PHP warning:
Declaration of LDAPAuthenticator :: userId ($ username) must be compatible with SQLAuthenticator:: userId () in C: \\ Apache2441x86 \\ htdocs \\ dotProject-2.1.9 \\ classes \\ authenticator.class.php on line 362 ,
reference: http: //jeahost/dotProject-2.1.9/index. php
// ui.class.php (728) says: Now that the password has been verified, see if they are allowed
// access the system
[Wed, October 9 00: 00: 48.239481 2019] [php7: notice] [pid 3404: tid 792] [client 127.0.0.1:49950] C: \\ Apache2441x86 \\ htdocs \\ dotProject-2.1.9 \\ classes \ \ ui.class.php (734): permission verification error, reference: http: //jeahost/dotProject-2.1.9/index.php

With this last data I ask for help

**Comment by ajdonnison** [comment]
The Declaration of LDAPAuthenticator issue should be resolved in the devel branch. There are a few ways to get this:
1. Go to the Code page and from the Branches/Tags dropdown select devel, then use the Clone or Download option
1. Directly download the devel version https://github.com/dotproject/dotProject/archive/devel.zip
