### ISSUE TITLE
Can't log in using alternate port

### ISSUE THREAD

**Issue by Riversiderepeat** [dotproject/dotProject#98]
Just like it says. Using an alternate port (8000), all logins fail from external machines. From the server host localhost:8000 can log in, but any machines attempting to get in using [ip]:8000, [alias}:8000 all fail. Changing the sever port back to 80 and all logins work fine. I must use an alternate port however since I have another server using port 80. Any suggestions? 

EDIT: This is odd. I just set up a reverse proxy in the other server using port 8000 and although accessing this way is throwing a lot of server errors, I WAS actually able to log in over the proxy. Weird.

**Comment by ajdonnison** [comment]
If you pull the devel branch, it now has a fix for this.
